# Generated by Django 4.2.6 on 2023-10-28 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_about_sociallink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
    ]
